### ISSUE TITLE
Can not import celltypist

### ISSUE THREAD

**Issue by Jiam1ng** [Teichlab/celltypist#78]
When I tried to import celltypist, it outputs the following errors:
import celltypist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dellstorage02/quj_lab/lijiaming/05_software/minoconda3/envs/celltypist_py3.8/lib/python3.8/site-packages/celltypist/__init__.py", line 2, in <module>
    from . import classifier, models, samples
  File "/dellstorage02/quj_lab/lijiaming/05_software/minoconda3/envs/celltypist_py3.8/lib/python3.8/site-packages/celltypist/classifier.py", line 3, in <module>
    import scanpy as sc
  File "/dellstorage02/quj_lab/lijiaming/05_software/minoconda3/envs/celltypist_py3.8/lib/python3.8/site-packages/scanpy/__init__.py", line 17, in <module>
    from . import plotting as pl
  File "/dellstorage02/quj_lab/lijiaming/05_software/minoconda3/envs/celltypist_py3.8/lib/python3.8/site-packages/scanpy/plotting/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/dellstorage02/quj_lab/lijiaming/05_software/minoconda3/envs/celltypist_py3.8/lib/python3.8/site-packages/scanpy/plotting/_anndata.py", line 28, in <module>
    from . import _utils
  File "/dellstorage02/quj_lab/lijiaming/05_software/minoconda3/envs/celltypist_py3.8/lib/python3.8/site-packages/scanpy/plotting/_utils.py", line 36, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
I have tried different versions of python, but they all do the same. Can someone please help me solve this issue?

**Comment by Jiam1ng** [comment]
I try to update scanpy to 1.9.2, and celltypist can be successfully imported.
